name: Publish Docker image
on:
  push:
  schedule:
    - cron: '40 18 1 * *'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_machine_branch:
          [
            [bionic-rocko, ek874, BSP-1.0.8],
            [bionic-rocko, hihope-rzg2h, BSP-1.0.8],
            [bionic-rocko, hihope-rzg2h, BSP-1.0.8],
            [bionic-rocko, hihope-rzg2m, BSP-1.0.8],
            [bionic-rocko, hihope-rzg2n, BSP-1.0.8],
          ]
    steps:
      - run: |
          echo TAGS="${{ matrix.base_machine_branch[1] }}-$(echo "${{ matrix.base_machine_branch[2] }}" | sed -e 's/^BSP-//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/yocto-rzg2-builder
            ghcr.io/anyakichi/yocto-rzg2-builder
          tags: ${{ env.TAGS }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            base=${{ matrix.base_machine_branch[0] }}
            meta_rzg2_branch=${{ matrix.base_machine_branch[2] }}
            yocto_machine=${{ matrix.base_machine_branch[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
